import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:latlong2/latlong.dart';

import '../constants/app_colors.dart';
import '../models/soil_compaction_point_model.dart';
import '../repositories/soil_compaction_point_repository.dart';
import '../services/soil_point_generator_service.dart';
import '../services/soil_analysis_service.dart';
import 'soil_map_visualization_screen.dart';
import 'soil_trajectory_mode_screen.dart';
import 'soil_laboratory_upload_screen.dart';
import 'soil_temporal_analysis_screen.dart';
import 'soil_report_generation_screen.dart';
import 'soil_bluetooth_collection_screen.dart';
import 'penetrometro_bluetooth_professional_screen.dart';
import '../../../models/talhao_model.dart';
import '../../../services/talhao_unified_loader_service.dart';

/// Tela principal do módulo de compactação e diagnóstico do solo
class SoilCompactionMainV2Screen extends StatefulWidget {
  const SoilCompactionMainV2Screen({Key? key}) : super(key: key);

  @override
  State<SoilCompactionMainV2Screen> createState() =>
      _SoilCompactionMainV2ScreenState();
}

class _SoilCompactionMainV2ScreenState
    extends State<SoilCompactionMainV2Screen> {
  final _talhaoLoader = TalhaoUnifiedLoaderService();
  List<TalhaoModel> _talhoes = [];
  TalhaoModel? _talhaoSelecionado;
  bool _isLoading = true;
  List<SoilCompactionPointModel> _pontos = [];

  /// Converte um ID de talhão textual (ex: UUID) para um inteiro estável
  /// Usamos os primeiros 8 dígitos hexadecimais como inteiro base 16
  int _talhaoIdToInt(String talhaoId) {
    final hex = talhaoId.replaceAll('-', '');
    final take = hex.length >= 8 ? hex.substring(0, 8) : hex.padRight(8, '0');
    return int.parse(take, radix: 16);
  }

  @override
  void initState() {
    super.initState();
    _carregarDados();
  }

  Future<void> _carregarDados() async {
    setState(() => _isLoading = true);

    try {
      final talhoes = await _talhaoLoader.carregarTalhoes();
      setState(() {
        _talhoes = talhoes;
        _isLoading = false;
      });
    } catch (e) {
      setState(() => _isLoading = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erro ao carregar dados: $e')),
        );
      }
    }
  }

  Future<void> _carregarPontosTalhao(int talhaoId) async {
    final repository = Provider.of<SoilCompactionPointRepository>(
      context,
      listen: false,
    );
    
    final pontos = await repository.getByTalhao(talhaoId);
    setState(() {
      _pontos = pontos;
    });
  }

  Future<void> _gerarPontosAutomaticos() async {
    if (_talhaoSelecionado == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Selecione um talhão')),
      );
      return;
    }

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => const Center(
        child: Card(
          child: Padding(
            padding: EdgeInsets.all(24.0),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                CircularProgressIndicator(),
                SizedBox(height: 16),
                Text('Gerando pontos de coleta...'),
              ],
            ),
          ),
        ),
      ),
    );

    try {
      final repository = Provider.of<SoilCompactionPointRepository>(
        context,
        listen: false,
      );

      // Verifica se já existem pontos auto-gerados
      final hasPoints = await repository.hasAutoGeneratedPoints(
        _talhaoIdToInt(_talhaoSelecionado!.id),
      );

      if (hasPoints) {
        Navigator.pop(context); // Fecha loading
        
        final confirma = await showDialog<bool>(
          context: context,
          builder: (context) => AlertDialog(
            title: const Text('Pontos Existentes'),
            content: const Text(
              'Já existem pontos gerados para este talhão. Deseja apagá-los e gerar novos?',
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(context, false),
                child: const Text('Cancelar'),
              ),
              ElevatedButton(
                onPressed: () => Navigator.pop(context, true),
                style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
                child: const Text('Substituir'),
              ),
            ],
          ),
        );

        if (confirma != true) return;

        // Mostra loading novamente
        if (mounted) {
          showDialog(
            context: context,
            barrierDismissible: false,
            builder: (context) => const Center(
              child: Card(
                child: Padding(
                  padding: EdgeInsets.all(24.0),
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      CircularProgressIndicator(),
                      SizedBox(height: 16),
                      Text('Gerando novos pontos...'),
                    ],
                  ),
                ),
              ),
            ),
          );
        }

        // Remove pontos antigos
        await repository.deleteAutoGeneratedPoints(_talhaoIdToInt(_talhaoSelecionado!.id));
      }

      // Coordenadas do talhão
      final polygonCoords = _talhaoSelecionado!.points;

      // Gera novos pontos
      final pontos = SoilPointGeneratorService.gerarPontosAutomaticos(
        talhaoId: _talhaoIdToInt(_talhaoSelecionado!.id),
        polygonCoordinates: polygonCoords,
        areaHectares: _talhaoSelecionado!.area,
      );

      // Salva no banco
      await repository.insertMany(pontos);

      // Atualiza lista
      await _carregarPontosTalhao(_talhaoIdToInt(_talhaoSelecionado!.id));

      if (mounted) {
        Navigator.pop(context); // Fecha loading
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('✅ ${pontos.length} pontos gerados com sucesso!'),
            backgroundColor: AppColors.success,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        Navigator.pop(context); // Fecha loading
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Erro: $e')),
        );
      }
    }
  }

  Future<void> _abrirMapa() async {
    if (_talhaoSelecionado == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Selecione um talhão')),
      );
      return;
    }

    final polygonCoords = _talhaoSelecionado!.points
        .toList();

    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => SoilMapVisualizationScreen(
          talhaoId: _talhaoIdToInt(_talhaoSelecionado!.id),
          nomeTalhao: _talhaoSelecionado!.name,
          polygonCoordinates: polygonCoords,
        ),
      ),
    );

    // Recarrega pontos após voltar do mapa
      _carregarPontosTalhao(_talhaoIdToInt(_talhaoSelecionado!.id));
  }

  Future<void> _abrirModoTrajeto() async {
    if (_talhaoSelecionado == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Selecione um talhão')),
      );
      return;
    }

    final polygonCoords = _talhaoSelecionado!.points
        .toList();

    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => SoilTrajectoryModeScreen(
          talhaoId: _talhaoIdToInt(_talhaoSelecionado!.id),
          nomeTalhao: _talhaoSelecionado!.name,
          polygonCoordinates: polygonCoords,
        ),
      ),
    );

    // Recarrega pontos após voltar do modo trajeto
      _carregarPontosTalhao(_talhaoIdToInt(_talhaoSelecionado!.id));
  }

  Future<void> _abrirUploadLaudos() async {
    if (_pontos.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Nenhum ponto de coleta encontrado')),
      );
      return;
    }

    // Mostra lista de pontos para seleção
    final pontoSelecionado = await showDialog<SoilCompactionPointModel>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Selecionar Ponto para Upload'),
        content: SizedBox(
          width: double.maxFinite,
          child: ListView.builder(
            shrinkWrap: true,
            itemCount: _pontos.length,
            itemBuilder: (context, index) {
              final ponto = _pontos[index];
              return ListTile(
                leading: CircleAvatar(
                  backgroundColor: AppColors.primaryColor,
                  child: Text(
                    ponto.pointCode.replaceAll('C-', ''),
                    style: const TextStyle(color: Colors.white),
                  ),
                ),
                title: Text(ponto.pointCode),
                subtitle: Text(
                  'Penetrometria: ${ponto.penetrometria?.toStringAsFixed(2) ?? "N/A"} MPa',
                ),
                onTap: () => Navigator.pop(context, ponto),
              );
            },
          ),
        ),
      ),
    );

    if (pontoSelecionado != null) {
      await Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => SoilLaboratoryUploadScreen(
            pointId: pontoSelecionado.id!,
            pointCode: pontoSelecionado.pointCode,
          ),
        ),
      );
    }
  }

  Future<void> _abrirAnalisesTemporais() async {
    if (_talhaoSelecionado == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Selecione um talhão')),
      );
      return;
    }

    final polygonCoords = _talhaoSelecionado!.points
        .toList();

    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => SoilTemporalAnalysisScreen(
          talhaoId: _talhaoIdToInt(_talhaoSelecionado!.id),
          nomeTalhao: _talhaoSelecionado!.name,
          polygonCoordinates: polygonCoords,
        ),
      ),
    );
  }

  Future<void> _abrirGeracaoRelatorios() async {
    if (_talhaoSelecionado == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Selecione um talhão')),
      );
      return;
    }

    final polygonCoords = _talhaoSelecionado!.points
        .toList();

    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => SoilReportGenerationScreen(
          talhaoId: _talhaoIdToInt(_talhaoSelecionado!.id),
          nomeTalhao: _talhaoSelecionado!.name,
          nomeFazenda: 'Fazenda Exemplo', // Em produção, viria do contexto
          polygonCoordinates: polygonCoords,
        ),
      ),
    );
  }

  Future<void> _abrirColetaBluetooth() async {
    if (_talhaoSelecionado == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Selecione um talhão')),
      );
      return;
    }

    final polygonCoords = _talhaoSelecionado!.points
        .toList();

    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => SoilBluetoothCollectionScreen(
          talhaoId: _talhaoIdToInt(_talhaoSelecionado!.id),
          nomeTalhao: _talhaoSelecionado!.name,
          polygonCoordinates: polygonCoords,
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.backgroundColor,
      appBar: AppBar(
        title: const Text(
          'Compactação e Diagnóstico do Solo',
          style: TextStyle(
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
        ),
        backgroundColor: AppColors.primaryColor,
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildInfoCard(),
                  const SizedBox(height: 16),
                  _buildSelecaoTalhao(),
                  const SizedBox(height: 16),
                  if (_talhaoSelecionado != null) ...[
                    _buildAcoesCard(),
                    const SizedBox(height: 16),
                    if (_pontos.isNotEmpty) _buildEstatisticasCard(),
                  ],
                ],
              ),
            ),
    );
  }

  Widget _buildInfoCard() {
    return Card(
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Container(
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(12),
          gradient: LinearGradient(
            colors: [
              AppColors.primaryColor.withOpacity(0.1),
              AppColors.primaryColor.withOpacity(0.05),
            ],
          ),
        ),
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: AppColors.primaryColor,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Icon(
                    Icons.info_outline,
                    color: Colors.white,
                    size: 24,
                  ),
                ),
                const SizedBox(width: 12),
                const Expanded(
                  child: Text(
                    'Sistema Avançado de Diagnóstico',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            const Text(
              '🌍 Georreferenciamento automático a cada 10 hectares\n'
              '📊 Análise completa de compactação e problemas do solo\n'
              '🗺️ Visualização em mapa com pontos coloridos\n'
              '🧠 Recomendações agronômicas automáticas\n'
              '🚶 Modo trajeto de avaliação com GPS ao vivo\n'
              '🧬 Upload e análise de laudos laboratoriais\n'
              '🤖 SoilSmart Engine - IA para diagnóstico cruzado\n'
              '📈 Análises temporais e mapas de tendência\n'
              '📄 Relatórios premium com mapas e gráficos\n'
              '📡 Coleta com penetrômetro Bluetooth em tempo real',
              style: TextStyle(height: 1.5),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildSelecaoTalhao() {
    return Card(
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: Colors.green,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Icon(
                    Icons.landscape,
                    color: Colors.white,
                    size: 20,
                  ),
                ),
                const SizedBox(width: 12),
                const Text(
                  'Selecionar Talhão',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            DropdownButtonFormField<TalhaoModel>(
              value: _talhaoSelecionado,
              decoration: const InputDecoration(
                border: OutlineInputBorder(),
                hintText: 'Escolha um talhão',
              ),
              items: _talhoes.map((talhao) {
                return DropdownMenuItem(
                  value: talhao,
                  child: Text(
                    '${talhao.name} (${talhao.area.toStringAsFixed(1)} ha)',
                  ),
                );
              }).toList(),
              onChanged: (talhao) async {
                setState(() {
                  _talhaoSelecionado = talhao;
                  _pontos = [];
                });
                if (talhao != null) {
                  await _carregarPontosTalhao(_talhaoIdToInt(talhao.id));
                }
              },
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildAcoesCard() {
    return Card(
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: Colors.blue,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Icon(
                    Icons.map,
                    color: Colors.white,
                    size: 20,
                  ),
                ),
                const SizedBox(width: 12),
                const Text(
                  'Ações',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _gerarPontosAutomaticos,
                icon: const Icon(Icons.auto_awesome),
                label: const Text('Gerar Pontos Automaticamente'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primaryColor,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _pontos.isNotEmpty ? _abrirMapa : null,
                icon: const Icon(Icons.map_outlined),
                label: const Text('Visualizar no Mapa'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.green,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _abrirModoTrajeto,
                icon: const Icon(Icons.directions_walk),
                label: const Text('Modo Trajeto de Avaliação'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.purple,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _abrirUploadLaudos,
                icon: const Icon(Icons.science),
                label: const Text('Upload de Laudos Laboratoriais'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.teal,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _abrirAnalisesTemporais,
                icon: const Icon(Icons.trending_up),
                label: const Text('Análises Temporais e Tendências'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.indigo,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _abrirGeracaoRelatorios,
                icon: const Icon(Icons.picture_as_pdf),
                label: const Text('Gerar Relatório Premium'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.red,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _abrirColetaBluetooth,
                icon: const Icon(Icons.bluetooth),
                label: const Text('Coleta com Penetrômetro Bluetooth'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.purple,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
            
            const SizedBox(height: 8),
            
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _abrirBluetoothProfissional,
                icon: const Icon(Icons.bluetooth_connected),
                label: const Text('Bluetooth Profissional'),
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.indigo,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildEstatisticasCard() {
    final estatisticas = SoilAnalysisService.calcularEstatisticas(_pontos);
    final classificacao = SoilAnalysisService.classificarTalhao(_pontos);
    final grupos = SoilAnalysisService.agruparPorNivel(_pontos);

    return Card(
      elevation: 2,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: Colors.orange,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Icon(
                    Icons.analytics,
                    color: Colors.white,
                    size: 20,
                  ),
                ),
                const SizedBox(width: 12),
                const Text(
                  'Estatísticas',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                _buildStatItem(
                  'Total',
                  '${estatisticas['totalPontos']}',
                  Icons.location_on,
                ),
                _buildStatItem(
                  'Medidos',
                  '${estatisticas['pontosComMedicao']}',
                  Icons.check_circle,
                ),
                _buildStatItem(
                  'Média',
                  '${classificacao['media'].toStringAsFixed(2)} MPa',
                  Icons.trending_up,
                ),
              ],
            ),
            const Divider(height: 24),
            _buildClassificacao(classificacao),
            const Divider(height: 24),
            const Text(
              'Distribuição por Nível:',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 8),
            ...grupos.entries.map((entry) {
              if (entry.value.isEmpty) return const SizedBox.shrink();
              return _buildNivelRow(entry.key, entry.value.length);
            }).toList(),
          ],
        ),
      ),
    );
  }

  Widget _buildStatItem(String label, String value, IconData icon) {
    return Column(
      children: [
        Icon(icon, size: 32, color: AppColors.primaryColor),
        const SizedBox(height: 4),
        Text(
          value,
          style: const TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        Text(
          label,
          style: const TextStyle(fontSize: 12, color: Colors.grey),
        ),
      ],
    );
  }

  Widget _buildClassificacao(Map<String, dynamic> classificacao) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Colors.blue.withOpacity(0.1),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            classificacao['classificacao'],
            style: const TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            classificacao['descricao'],
            style: const TextStyle(fontSize: 13),
          ),
          const SizedBox(height: 8),
          Text(
            '💡 ${classificacao['recomendacao']}',
            style: const TextStyle(
              fontSize: 13,
              fontStyle: FontStyle.italic,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildNivelRow(String nivel, int quantidade) {
    Color cor;
    switch (nivel) {
      case 'Solto':
        cor = const Color(0xFF4CAF50);
        break;
      case 'Moderado':
        cor = const Color(0xFFFFEB3B);
        break;
      case 'Alto':
        cor = const Color(0xFFFF9800);
        break;
      case 'Crítico':
        cor = const Color(0xFFF44336);
        break;
      default:
        cor = const Color(0xFF9E9E9E);
    }

    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Row(
        children: [
          Container(
            width: 16,
            height: 16,
            decoration: BoxDecoration(
              color: cor,
              shape: BoxShape.circle,
            ),
          ),
          const SizedBox(width: 8),
          Text('$nivel:'),
          const Spacer(),
          Text(
            '$quantidade ${quantidade == 1 ? "ponto" : "pontos"}',
            style: const TextStyle(fontWeight: FontWeight.bold),
          ),
        ],
      ),
    );
  }

  Future<void> _abrirBluetoothProfissional() async {
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => const PenetrometroBluetoothProfessionalScreen(),
      ),
    );
  }
}

