/// 📊 Model: Estágio Fenológico (Escala BBCH)
/// 
/// Este modelo representa um estágio fenológico específico,
/// baseado na escala BBCH internacional. Contém as regras
/// para identificação automática de cada estágio.
/// 
/// Autor: FortSmart Agro
/// Data: Outubro 2025

import 'package:flutter/material.dart';

class PhenologicalStageModel {
  /// Código do estágio (ex: V4, R1, R5)
  final String codigo;
  
  /// Nome descritivo do estágio
  final String nome;
  
  /// Descrição detalhada
  final String descricao;
  
  /// Tipo de cultura (soja, milho, feijao, etc.)
  final String cultura;
  
  /// Categoria (vegetativo ou reprodutivo)
  final StageCategory categoria;
  
  /// Código BBCH numérico (0-99)
  final int codigoBBCH;
  
  /// Faixa de dias após emergência (mínimo)
  final int? daeMinimo;
  
  /// Faixa de dias após emergência (máximo)
  final int? daeMaximo;
  
  /// Altura esperada mínima (cm)
  final double? alturaMinimaCm;
  
  /// Altura esperada máxima (cm)
  final double? alturaMaximaCm;
  
  /// Número mínimo de folhas
  final int? numeroFolhasMinimo;
  
  /// Número máximo de folhas
  final int? numeroFolhasMaximo;
  
  /// Cor associada ao estágio
  final Color cor;
  
  /// Ícone representativo
  final IconData icone;
  
  /// Recomendações agronômicas
  final List<String> recomendacoes;

  PhenologicalStageModel({
    required this.codigo,
    required this.nome,
    required this.descricao,
    required this.cultura,
    required this.categoria,
    required this.codigoBBCH,
    this.daeMinimo,
    this.daeMaximo,
    this.alturaMinimaCm,
    this.alturaMaximaCm,
    this.numeroFolhasMinimo,
    this.numeroFolhasMaximo,
    this.cor = Colors.green,
    this.icone = Icons.eco,
    this.recomendacoes = const [],
  });

  /// Converter para Map
  Map<String, dynamic> toMap() {
    return {
      'codigo': codigo,
      'nome': nome,
      'descricao': descricao,
      'cultura': cultura,
      'categoria': categoria.toString(),
      'codigoBBCH': codigoBBCH,
      'daeMinimo': daeMinimo,
      'daeMaximo': daeMaximo,
      'alturaMinimaCm': alturaMinimaCm,
      'alturaMaximaCm': alturaMaximaCm,
      'numeroFolhasMinimo': numeroFolhasMinimo,
      'numeroFolhasMaximo': numeroFolhasMaximo,
      'cor': cor.value,
      'recomendacoes': recomendacoes.join('|'),
    };
  }

  /// Criar a partir de Map
  factory PhenologicalStageModel.fromMap(Map<String, dynamic> map) {
    return PhenologicalStageModel(
      codigo: map['codigo'] as String,
      nome: map['nome'] as String,
      descricao: map['descricao'] as String,
      cultura: map['cultura'] as String,
      categoria: _parseCategory(map['categoria'] as String),
      codigoBBCH: map['codigoBBCH'] as int,
      daeMinimo: map['daeMinimo'] as int?,
      daeMaximo: map['daeMaximo'] as int?,
      alturaMinimaCm: map['alturaMinimaCm'] as double?,
      alturaMaximaCm: map['alturaMaximaCm'] as double?,
      numeroFolhasMinimo: map['numeroFolhasMinimo'] as int?,
      numeroFolhasMaximo: map['numeroFolhasMaximo'] as int?,
      cor: Color(map['cor'] as int),
      recomendacoes: (map['recomendacoes'] as String?)?.split('|').where((s) => s.isNotEmpty).toList() ?? [],
    );
  }

  static StageCategory _parseCategory(String category) {
    if (category.contains('vegetativo')) return StageCategory.vegetativo;
    if (category.contains('reprodutivo')) return StageCategory.reprodutivo;
    return StageCategory.vegetativo;
  }

  @override
  String toString() => 'PhenologicalStageModel($codigo - $nome)';
}

/// Enum: Categoria do estágio fenológico
enum StageCategory {
  vegetativo,
  reprodutivo,
}

/// 🌾 Banco de Dados de Estágios Fenológicos
class PhenologicalStageDatabase {
  /// Obter todos os estágios de uma cultura
  static List<PhenologicalStageModel> getEstagiosPorCultura(String cultura) {
    switch (cultura.toLowerCase()) {
      case 'soja':
        return _estagiosSoja;
      case 'milho':
        return _estagiosMilho;
      case 'feijao':
      case 'feijão':
        return _estagiosFeijao;
      case 'algodao':
      case 'algodão':
        return _estagiosAlgodao;
      case 'cana':
      case 'cana-de-açucar':
      case 'cana-de-acucar':
      case 'cana de açúcar':
      case 'cana de acucar':
        return _estagiosCana;
      case 'arroz':
        return _estagiosArroz;
      case 'trigo':
        return _estagiosTrigo;
      case 'sorgo':
        return _estagiosSorgo;
      case 'girassol':
        return _estagiosGirassol;
      case 'gergelim':
        return _estagiosGergelim;
      case 'tomate':
        return _estagiosTomate;
      case 'aveia':
        return _estagiosAveia;
      default:
        return [];
    }
  }

  /// 🌱 Estágios Fenológicos da SOJA
  static final List<PhenologicalStageModel> _estagiosSoja = [
    // VEGETATIVO
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Cotilédones acima da superfície do solo',
      cultura: 'soja',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 5,
      daeMaximo: 10,
      alturaMinimaCm: 5,
      alturaMaximaCm: 10,
      cor: Colors.lightGreen,
      icone: Icons.spa,
      recomendacoes: [
        'Monitorar emergência uniforme',
        'Verificar população de plantas',
        'Atenção a pragas de solo',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'VC',
      nome: 'Cotilédone',
      descricao: 'Cotilédones completamente expandidos',
      cultura: 'soja',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 11,
      daeMinimo: 7,
      daeMaximo: 15,
      alturaMinimaCm: 8,
      alturaMaximaCm: 15,
      cor: Colors.green,
      icone: Icons.eco,
      recomendacoes: [
        'Verificar estande final',
        'Controle de plantas daninhas',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'V1',
      nome: 'Primeira Folha Trifoliolada',
      descricao: 'Primeiro trifólio completamente desenvolvido',
      cultura: 'soja',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 12,
      daeMinimo: 10,
      daeMaximo: 20,
      alturaMinimaCm: 15,
      alturaMaximaCm: 25,
      numeroFolhasMinimo: 1,
      numeroFolhasMaximo: 1,
      cor: Colors.green,
      icone: Icons.eco,
      recomendacoes: [
        'Monitorar pragas iniciais',
        'Avaliar nutrição inicial',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'V2',
      nome: 'Segunda Folha Trifoliolada',
      descricao: 'Segundo trifólio completamente desenvolvido',
      cultura: 'soja',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 13,
      daeMinimo: 15,
      daeMaximo: 25,
      alturaMinimaCm: 20,
      alturaMaximaCm: 35,
      numeroFolhasMinimo: 2,
      numeroFolhasMaximo: 2,
      cor: Colors.green,
      icone: Icons.eco,
      recomendacoes: [
        'Avaliar desenvolvimento vegetativo',
        'Monitorar doenças foliares',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'V3',
      nome: 'Terceira Folha Trifoliolada',
      descricao: 'Terceiro trifólio completamente desenvolvido',
      cultura: 'soja',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 14,
      daeMinimo: 20,
      daeMaximo: 30,
      alturaMinimaCm: 30,
      alturaMaximaCm: 45,
      numeroFolhasMinimo: 3,
      numeroFolhasMaximo: 3,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V4',
      nome: 'Quarta Folha Trifoliolada',
      descricao: 'Quarto trifólio completamente desenvolvido',
      cultura: 'soja',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 15,
      daeMinimo: 25,
      daeMaximo: 35,
      alturaMinimaCm: 40,
      alturaMaximaCm: 60,
      numeroFolhasMinimo: 4,
      numeroFolhasMaximo: 4,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    
    // REPRODUTIVO
    PhenologicalStageModel(
      codigo: 'R1',
      nome: 'Início do Florescimento',
      descricao: 'Uma flor aberta em qualquer nó da haste principal',
      cultura: 'soja',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 60,
      daeMinimo: 35,
      daeMaximo: 50,
      alturaMinimaCm: 50,
      alturaMaximaCm: 80,
      cor: Colors.purple,
      icone: Icons.local_florist,
      recomendacoes: [
        'Monitorar pragas da fase reprodutiva',
        'Avaliar necessidade de fungicida',
        'Período crítico de déficit hídrico',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'R2',
      nome: 'Florescimento Pleno',
      descricao: 'Flor aberta em um dos dois últimos nós da haste principal',
      cultura: 'soja',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 65,
      daeMinimo: 40,
      daeMaximo: 60,
      cor: Colors.purple,
      icone: Icons.local_florist,
    ),
    PhenologicalStageModel(
      codigo: 'R3',
      nome: 'Início da Formação de Vagens',
      descricao: 'Vagem com até 1,5 cm em um dos 4 últimos nós',
      cultura: 'soja',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 71,
      daeMinimo: 45,
      daeMaximo: 65,
      cor: Colors.orange,
      icone: Icons.apps,
      recomendacoes: [
        'Fase crítica de definição de produtividade',
        'Controle rigoroso de pragas',
        'Evitar déficit hídrico',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'R4',
      nome: 'Vagem Completamente Desenvolvida',
      descricao: 'Vagem com 2 a 4 cm em um dos 4 últimos nós',
      cultura: 'soja',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 75,
      daeMinimo: 50,
      daeMaximo: 70,
      cor: Colors.orange,
      icone: Icons.apps,
    ),
    PhenologicalStageModel(
      codigo: 'R5',
      nome: 'Início do Enchimento de Grãos',
      descricao: 'Grão com até 3 mm em vagem de um dos 4 últimos nós',
      cultura: 'soja',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 80,
      daeMinimo: 55,
      daeMaximo: 80,
      cor: Colors.deepOrange,
      icone: Icons.grain,
      recomendacoes: [
        'Fase de ganho de peso de grãos',
        'Monitorar doenças de final de ciclo',
        'Manter sanidade foliar',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'R6',
      nome: 'Grão Completamente Cheio',
      descricao: 'Vagem com grão verde preenchendo a cavidade',
      cultura: 'soja',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 85,
      daeMinimo: 65,
      daeMaximo: 90,
      cor: Colors.brown,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'R7',
      nome: 'Início da Maturação',
      descricao: 'Uma vagem normal na haste principal com coloração madura',
      cultura: 'soja',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 89,
      daeMinimo: 80,
      daeMaximo: 100,
      cor: Colors.brown,
      icone: Icons.eco_outlined,
      recomendacoes: [
        'Planejamento de dessecação (se necessário)',
        'Avaliar ponto de colheita',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'R8',
      nome: 'Maturação Plena',
      descricao: '95% das vagens com coloração madura',
      cultura: 'soja',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 92,
      daeMinimo: 90,
      daeMaximo: 120,
      cor: Colors.brown,
      icone: Icons.eco_outlined,
      recomendacoes: [
        'Ponto ideal de colheita próximo',
        'Monitorar umidade dos grãos',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'R9',
      nome: 'Maturação de Colheita',
      descricao: 'Planta com folhas caídas, vagens secas',
      cultura: 'soja',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 99,
      daeMinimo: 100,
      daeMaximo: 140,
      cor: Colors.grey,
      icone: Icons.grass,
      recomendacoes: [
        'Colheita imediata',
        'Evitar perdas por degrane',
      ],
    ),
  ];

  /// 🌽 Estágios Fenológicos do MILHO
  static final List<PhenologicalStageModel> _estagiosMilho = [
    // VEGETATIVO
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Coleoptile visível acima do solo',
      cultura: 'milho',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 4,
      daeMaximo: 10,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'V2',
      nome: 'Segunda Folha',
      descricao: 'Segunda folha completamente desenvolvida',
      cultura: 'milho',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 12,
      daeMinimo: 10,
      daeMaximo: 20,
      numeroFolhasMinimo: 2,
      numeroFolhasMaximo: 2,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V4',
      nome: 'Quarta Folha',
      descricao: 'Quarta folha completamente desenvolvida',
      cultura: 'milho',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 14,
      daeMinimo: 18,
      daeMaximo: 30,
      numeroFolhasMinimo: 4,
      numeroFolhasMaximo: 4,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V6',
      nome: 'Sexta Folha',
      descricao: 'Sexta folha completamente desenvolvida',
      cultura: 'milho',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 16,
      daeMinimo: 25,
      daeMaximo: 40,
      numeroFolhasMinimo: 6,
      numeroFolhasMaximo: 6,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'VT',
      nome: 'Pendoamento',
      descricao: 'Pendão completamente visível',
      cultura: 'milho',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 59,
      daeMinimo: 50,
      daeMaximo: 70,
      cor: Colors.purple,
      icone: Icons.star,
    ),
    
    // REPRODUTIVO
    PhenologicalStageModel(
      codigo: 'R1',
      nome: 'Embonecamento',
      descricao: 'Estigma visível',
      cultura: 'milho',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 61,
      daeMinimo: 55,
      daeMaximo: 75,
      cor: Colors.orange,
      icone: Icons.local_florist,
      recomendacoes: [
        'Período crítico de água',
        'Definição de número de grãos',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'R2',
      nome: 'Grão Leitoso',
      descricao: 'Grãos com líquido claro',
      cultura: 'milho',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 73,
      daeMinimo: 65,
      daeMaximo: 85,
      cor: Colors.amber,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'R3',
      nome: 'Grão Pastoso',
      descricao: 'Grãos amarelos e pastosos',
      cultura: 'milho',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 85,
      daeMinimo: 75,
      daeMaximo: 95,
      cor: Colors.orange,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'R4',
      nome: 'Grão Farináceo',
      descricao: 'Grãos duros na parte superior',
      cultura: 'milho',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 87,
      daeMinimo: 85,
      daeMaximo: 105,
      cor: Colors.brown,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'R5',
      nome: 'Grão Duro (Dentado)',
      descricao: 'Grãos duros e brilhantes',
      cultura: 'milho',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 89,
      daeMinimo: 95,
      daeMaximo: 115,
      cor: Colors.brown,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'R6',
      nome: 'Maturação Fisiológica',
      descricao: 'Camada preta visível na base do grão',
      cultura: 'milho',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 92,
      daeMinimo: 110,
      daeMaximo: 140,
      cor: Colors.grey,
      icone: Icons.eco_outlined,
      recomendacoes: [
        'Ponto de colheita para silagem',
        'Aguardar secagem para grãos',
      ],
    ),
  ];

  /// 🫘 Estágios Fenológicos do FEIJÃO
  static final List<PhenologicalStageModel> _estagiosFeijao = [
    PhenologicalStageModel(
      codigo: 'V0',
      nome: 'Germinação',
      descricao: 'Emissão da radícula',
      cultura: 'feijao',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 5,
      daeMinimo: 3,
      daeMaximo: 8,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'V1',
      nome: 'Emergência',
      descricao: 'Cotilédones acima do solo',
      cultura: 'feijao',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 5,
      daeMaximo: 12,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V2',
      nome: 'Folhas Primárias',
      descricao: 'Folhas primárias completamente expandidas',
      cultura: 'feijao',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 12,
      daeMinimo: 10,
      daeMaximo: 18,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V3',
      nome: 'Primeira Folha Trifoliolada',
      descricao: 'Primeiro trifólio completamente expandido',
      cultura: 'feijao',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 13,
      daeMinimo: 15,
      daeMaximo: 25,
      numeroFolhasMinimo: 1,
      numeroFolhasMaximo: 1,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'R5',
      nome: 'Pré-Floração',
      descricao: 'Botões florais visíveis',
      cultura: 'feijao',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 55,
      daeMinimo: 25,
      daeMaximo: 35,
      cor: Colors.purple,
      icone: Icons.local_florist,
    ),
    PhenologicalStageModel(
      codigo: 'R6',
      nome: 'Floração',
      descricao: 'Primeira flor aberta',
      cultura: 'feijao',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 60,
      daeMinimo: 30,
      daeMaximo: 45,
      cor: Colors.purple,
      icone: Icons.local_florist,
    ),
    PhenologicalStageModel(
      codigo: 'R7',
      nome: 'Formação de Vagens',
      descricao: 'Primeira vagem com até 2 cm',
      cultura: 'feijao',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 71,
      daeMinimo: 35,
      daeMaximo: 50,
      cor: Colors.orange,
      icone: Icons.apps,
    ),
    PhenologicalStageModel(
      codigo: 'R8',
      nome: 'Enchimento de Vagens',
      descricao: 'Vagens com tamanho final',
      cultura: 'feijao',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 80,
      daeMinimo: 45,
      daeMaximo: 65,
      cor: Colors.deepOrange,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'R9',
      nome: 'Maturação',
      descricao: 'Vagens secas, grãos duros',
      cultura: 'feijao',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 92,
      daeMinimo: 70,
      daeMaximo: 90,
      cor: Colors.brown,
      icone: Icons.eco_outlined,
    ),
  ];

  /// 🌾 Estágios Fenológicos do ALGODÃO
  static final List<PhenologicalStageModel> _estagiosAlgodao = [
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Cotilédones visíveis acima do solo',
      cultura: 'algodao',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 5,
      daeMaximo: 12,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'V1',
      nome: 'Primeira Folha Verdadeira',
      descricao: 'Primeira folha verdadeira completamente expandida',
      cultura: 'algodao',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 11,
      daeMinimo: 12,
      daeMaximo: 20,
      numeroFolhasMinimo: 1,
      numeroFolhasMaximo: 1,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V4',
      nome: 'Quarta Folha Verdadeira',
      descricao: 'Quarta folha verdadeira expandida',
      cultura: 'algodao',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 14,
      daeMinimo: 25,
      daeMaximo: 35,
      numeroFolhasMinimo: 4,
      numeroFolhasMaximo: 4,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'B1',
      nome: 'Primeiro Botão Floral',
      descricao: 'Primeiro botão floral visível',
      cultura: 'algodao',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 51,
      daeMinimo: 35,
      daeMaximo: 50,
      cor: Colors.purple,
      icone: Icons.fiber_manual_record,
      recomendacoes: [
        'Início da fase reprodutiva',
        'Intensificar monitoramento de pragas',
        'Atenção especial ao bicudo',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'F1',
      nome: 'Primeira Flor Aberta',
      descricao: 'Primeira flor completamente aberta',
      cultura: 'algodao',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 60,
      daeMinimo: 45,
      daeMaximo: 65,
      cor: Colors.pink,
      icone: Icons.local_florist,
    ),
    PhenologicalStageModel(
      codigo: 'C1',
      nome: 'Primeiro Capulho',
      descricao: 'Primeiro capulho formado',
      cultura: 'algodao',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 70,
      daeMinimo: 65,
      daeMaximo: 90,
      cor: Colors.orange,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'C2',
      nome: 'Capulho Maduro',
      descricao: 'Capulhos começando a abrir',
      cultura: 'algodao',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 85,
      daeMinimo: 110,
      daeMaximo: 140,
      cor: Colors.brown,
      icone: Icons.cloud,
      recomendacoes: [
        'Planejamento de colheita',
        'Avaliar dessecação (se necessário)',
        'Monitorar umidade',
      ],
    ),
  ];

  /// 🌰 Estágios Fenológicos do GERGELIM
  static final List<PhenologicalStageModel> _estagiosGergelim = [
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Cotilédones visíveis acima do solo',
      cultura: 'gergelim',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 5,
      daeMaximo: 10,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'V2',
      nome: 'Segundo Par de Folhas',
      descricao: 'Segundo par de folhas verdadeiras expandido',
      cultura: 'gergelim',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 12,
      daeMinimo: 12,
      daeMaximo: 20,
      numeroFolhasMinimo: 2,
      numeroFolhasMaximo: 2,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V4',
      nome: 'Quarto Par de Folhas',
      descricao: 'Quarto par de folhas expandido',
      cultura: 'gergelim',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 14,
      daeMinimo: 20,
      daeMaximo: 30,
      numeroFolhasMinimo: 4,
      numeroFolhasMaximo: 4,
      alturaMinimaCm: 20,
      alturaMaximaCm: 40,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'R1',
      nome: 'Início do Florescimento',
      descricao: 'Primeiras flores abertas',
      cultura: 'gergelim',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 61,
      daeMinimo: 35,
      daeMaximo: 50,
      cor: Colors.white,
      icone: Icons.local_florist,
      recomendacoes: [
        'Período sensível ao déficit hídrico',
        'Garantir nutrição adequada',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'R2',
      nome: 'Floração Plena',
      descricao: 'Floração no terço médio da planta',
      cultura: 'gergelim',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 65,
      daeMinimo: 45,
      daeMaximo: 65,
      cor: Colors.white,
      icone: Icons.local_florist,
    ),
    PhenologicalStageModel(
      codigo: 'R3',
      nome: 'Formação de Cápsulas',
      descricao: 'Primeiras cápsulas formadas',
      cultura: 'gergelim',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 71,
      daeMinimo: 55,
      daeMaximo: 75,
      cor: Colors.green,
      icone: Icons.crop_square,
    ),
    PhenologicalStageModel(
      codigo: 'R5',
      nome: 'Enchimento de Cápsulas',
      descricao: 'Cápsulas em enchimento ativo',
      cultura: 'gergelim',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 81,
      daeMinimo: 70,
      daeMaximo: 90,
      cor: Colors.brown,
      icone: Icons.crop_square,
    ),
    PhenologicalStageModel(
      codigo: 'R7',
      nome: 'Início da Maturação',
      descricao: 'Primeiras cápsulas amadurecendo',
      cultura: 'gergelim',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 87,
      daeMinimo: 85,
      daeMaximo: 100,
      cor: Colors.brown,
      icone: Icons.check_circle,
    ),
    PhenologicalStageModel(
      codigo: 'R9',
      nome: 'Maturação de Colheita',
      descricao: 'Cápsulas secas, sementes maduras',
      cultura: 'gergelim',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 92,
      daeMinimo: 95,
      daeMaximo: 120,
      cor: Colors.brown,
      icone: Icons.eco_outlined,
      recomendacoes: [
        'Ponto de colheita',
        'Evitar perdas por deiscência das cápsulas',
      ],
    ),
  ];

  /// 🌾 Estágios Fenológicos da CANA-DE-AÇÚCAR
  static final List<PhenologicalStageModel> _estagiosCana = [
    PhenologicalStageModel(
      codigo: 'G',
      nome: 'Germinação',
      descricao: 'Brotação das gemas',
      cultura: 'cana',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 5,
      daeMinimo: 15,
      daeMaximo: 30,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'PE',
      nome: 'Perfilhamento',
      descricao: 'Emissão de perfilhos',
      cultura: 'cana',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 21,
      daeMinimo: 40,
      daeMaximo: 90,
      cor: Colors.green,
      icone: Icons.grass,
      recomendacoes: [
        'Fase crítica para definição de população de colmos',
        'Garantir boa disponibilidade de água e nutrientes',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'CE',
      nome: 'Crescimento dos Colmos',
      descricao: 'Alongamento ativo dos colmos',
      cultura: 'cana',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 35,
      daeMinimo: 100,
      daeMaximo: 200,
      cor: Colors.green,
      icone: Icons.height,
    ),
    PhenologicalStageModel(
      codigo: 'MA',
      nome: 'Maturação',
      descricao: 'Acúmulo de sacarose nos colmos',
      cultura: 'cana',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 85,
      daeMinimo: 300,
      daeMaximo: 360,
      cor: Colors.brown,
      icone: Icons.eco,
      recomendacoes: [
        'Período de acúmulo de açúcar',
        'Avaliar maturadores (se aplicável)',
        'Planejamento de colheita',
      ],
    ),
  ];

  /// 🍚 Estágios Fenológicos do ARROZ
  static final List<PhenologicalStageModel> _estagiosArroz = [
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Coleoptile visível acima do solo',
      cultura: 'arroz',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 5,
      daeMaximo: 12,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'V3',
      nome: 'Terceira Folha',
      descricao: 'Terceira folha completamente expandida',
      cultura: 'arroz',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 13,
      daeMinimo: 15,
      daeMaximo: 25,
      numeroFolhasMinimo: 3,
      numeroFolhasMaximo: 3,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'PE',
      nome: 'Perfilhamento',
      descricao: 'Emissão ativa de perfilhos',
      cultura: 'arroz',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 25,
      daeMinimo: 25,
      daeMaximo: 45,
      cor: Colors.green,
      icone: Icons.grass,
    ),
    PhenologicalStageModel(
      codigo: 'IP',
      nome: 'Iniciação da Panícula',
      descricao: 'Início da diferenciação da panícula',
      cultura: 'arroz',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 41,
      daeMinimo: 45,
      daeMaximo: 65,
      cor: Colors.lightGreen,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'EP',
      nome: 'Emborrachamento',
      descricao: 'Panícula no interior da bainha',
      cultura: 'arroz',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 45,
      daeMinimo: 65,
      daeMaximo: 80,
      cor: Colors.green,
      icone: Icons.expand,
    ),
    PhenologicalStageModel(
      codigo: 'FL',
      nome: 'Floração',
      descricao: 'Antese - flores abertas',
      cultura: 'arroz',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 65,
      daeMinimo: 80,
      daeMaximo: 95,
      cor: Colors.yellow,
      icone: Icons.local_florist,
      recomendacoes: [
        'Período crítico de água',
        'Definição do número de grãos',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'GL',
      nome: 'Grão Leitoso',
      descricao: 'Grãos com conteúdo leitoso',
      cultura: 'arroz',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 75,
      daeMinimo: 95,
      daeMaximo: 110,
      cor: Colors.amber,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'GF',
      nome: 'Grão Farináceo',
      descricao: 'Grãos com consistência farinhácea',
      cultura: 'arroz',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 85,
      daeMinimo: 110,
      daeMaximo: 125,
      cor: Colors.orange,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'MF',
      nome: 'Maturação Fisiológica',
      descricao: 'Grãos duros, panícula curvada',
      cultura: 'arroz',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 92,
      daeMinimo: 125,
      daeMaximo: 140,
      cor: Colors.brown,
      icone: Icons.grain,
      recomendacoes: [
        'Ponto de colheita próximo',
        'Avaliar umidade dos grãos',
      ],
    ),
  ];

  /// 🌾 Estágios Fenológicos do TRIGO
  static final List<PhenologicalStageModel> _estagiosTrigo = [
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Coleoptile visível',
      cultura: 'trigo',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 7,
      daeMaximo: 14,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'AP',
      nome: 'Afilhamento',
      descricao: 'Emissão de afilhos',
      cultura: 'trigo',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 21,
      daeMinimo: 20,
      daeMaximo: 40,
      cor: Colors.green,
      icone: Icons.grass,
    ),
    PhenologicalStageModel(
      codigo: 'EL',
      nome: 'Elongação',
      descricao: 'Alongamento do colmo',
      cultura: 'trigo',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 31,
      daeMinimo: 40,
      daeMaximo: 60,
      cor: Colors.green,
      icone: Icons.height,
    ),
    PhenologicalStageModel(
      codigo: 'EB',
      nome: 'Emborrachamento',
      descricao: 'Espiga no interior da bainha',
      cultura: 'trigo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 45,
      daeMinimo: 60,
      daeMaximo: 75,
      cor: Colors.lightGreen,
      icone: Icons.expand,
    ),
    PhenologicalStageModel(
      codigo: 'ES',
      nome: 'Espigamento',
      descricao: 'Espiga completamente visível',
      cultura: 'trigo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 55,
      daeMinimo: 75,
      daeMaximo: 85,
      cor: Colors.amber,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'FL',
      nome: 'Floração',
      descricao: 'Anteras visíveis',
      cultura: 'trigo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 65,
      daeMinimo: 85,
      daeMaximo: 95,
      cor: Colors.yellow,
      icone: Icons.local_florist,
    ),
    PhenologicalStageModel(
      codigo: 'GL',
      nome: 'Grão Leitoso',
      descricao: 'Grãos com líquido leitoso',
      cultura: 'trigo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 75,
      daeMinimo: 95,
      daeMaximo: 110,
      cor: Colors.amber,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'GM',
      nome: 'Grão Massa',
      descricao: 'Grãos com consistência pastosa',
      cultura: 'trigo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 85,
      daeMinimo: 110,
      daeMaximo: 125,
      cor: Colors.orange,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'MF',
      nome: 'Maturação',
      descricao: 'Grãos duros, planta seca',
      cultura: 'trigo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 92,
      daeMinimo: 125,
      daeMaximo: 140,
      cor: Colors.brown,
      icone: Icons.grain,
      recomendacoes: [
        'Ponto de colheita',
        'Evitar perdas por degrane',
      ],
    ),
  ];

  /// 🌾 Estágios Fenológicos do SORGO
  static final List<PhenologicalStageModel> _estagiosSorgo = [
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Coleoptile visível',
      cultura: 'sorgo',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 5,
      daeMaximo: 12,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'V3',
      nome: 'Terceira Folha',
      descricao: 'Terceira folha expandida',
      cultura: 'sorgo',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 13,
      daeMinimo: 15,
      daeMaximo: 25,
      numeroFolhasMinimo: 3,
      numeroFolhasMaximo: 3,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V6',
      nome: 'Sexta Folha',
      descricao: 'Sexta folha expandida',
      cultura: 'sorgo',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 16,
      daeMinimo: 30,
      daeMaximo: 45,
      numeroFolhasMinimo: 6,
      numeroFolhasMaximo: 6,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'BF',
      nome: 'Diferenciação da Panícula',
      descricao: 'Início da formação da panícula',
      cultura: 'sorgo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 41,
      daeMinimo: 45,
      daeMaximo: 60,
      cor: Colors.lightGreen,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'EB',
      nome: 'Emborrachamento',
      descricao: 'Panícula no interior da bainha',
      cultura: 'sorgo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 45,
      daeMinimo: 60,
      daeMaximo: 75,
      cor: Colors.green,
      icone: Icons.expand,
    ),
    PhenologicalStageModel(
      codigo: 'FL',
      nome: 'Floração',
      descricao: 'Anteras visíveis, panícula exposta',
      cultura: 'sorgo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 65,
      daeMinimo: 75,
      daeMaximo: 90,
      cor: Colors.purple,
      icone: Icons.local_florist,
    ),
    PhenologicalStageModel(
      codigo: 'GL',
      nome: 'Grão Leitoso',
      descricao: 'Grãos com conteúdo leitoso',
      cultura: 'sorgo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 75,
      daeMinimo: 90,
      daeMaximo: 105,
      cor: Colors.amber,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'GF',
      nome: 'Grão Farináceo',
      descricao: 'Grãos duros',
      cultura: 'sorgo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 85,
      daeMinimo: 105,
      daeMaximo: 120,
      cor: Colors.brown,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'MF',
      nome: 'Maturação Fisiológica',
      descricao: 'Grãos completamente maduros',
      cultura: 'sorgo',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 92,
      daeMinimo: 120,
      daeMaximo: 135,
      cor: Colors.brown,
      icone: Icons.grain,
    ),
  ];

  /// 🌻 Estágios Fenológicos do GIRASSOL
  static final List<PhenologicalStageModel> _estagiosGirassol = [
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Cotilédones visíveis',
      cultura: 'girassol',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 7,
      daeMaximo: 14,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'V4',
      nome: 'Quatro Pares de Folhas',
      descricao: 'Quatro pares de folhas expandidas',
      cultura: 'girassol',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 14,
      daeMinimo: 20,
      daeMaximo: 30,
      numeroFolhasMinimo: 4,
      numeroFolhasMaximo: 4,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V8',
      nome: 'Oito Pares de Folhas',
      descricao: 'Oito pares de folhas expandidas',
      cultura: 'girassol',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 18,
      daeMinimo: 35,
      daeMaximo: 50,
      numeroFolhasMinimo: 8,
      numeroFolhasMaximo: 8,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'R1',
      nome: 'Início do Botão Floral',
      descricao: 'Botão floral visível no ápice',
      cultura: 'girassol',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 51,
      daeMinimo: 50,
      daeMaximo: 65,
      cor: Colors.yellow,
      icone: Icons.fiber_manual_record,
    ),
    PhenologicalStageModel(
      codigo: 'R4',
      nome: 'Abertura do Capítulo',
      descricao: 'Flores do disco começando a abrir',
      cultura: 'girassol',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 61,
      daeMinimo: 65,
      daeMaximo: 75,
      cor: Colors.yellow,
      icone: Icons.wb_sunny,
    ),
    PhenologicalStageModel(
      codigo: 'R5',
      nome: 'Floração Plena',
      descricao: '50% das flores do disco abertas',
      cultura: 'girassol',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 65,
      daeMinimo: 75,
      daeMaximo: 85,
      cor: Colors.orange,
      icone: Icons.wb_sunny,
      recomendacoes: [
        'Período crítico de água',
        'Definição do número de aquênios',
        'Monitorar polinização',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'R6',
      nome: 'Fim da Floração',
      descricao: 'Flores murchas, início do enchimento',
      cultura: 'girassol',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 71,
      daeMinimo: 85,
      daeMaximo: 95,
      cor: Colors.brown,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'R9',
      nome: 'Maturação Fisiológica',
      descricao: 'Aquênios maduros, capítulo voltado para baixo',
      cultura: 'girassol',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 92,
      daeMinimo: 110,
      daeMaximo: 130,
      cor: Colors.brown,
      icone: Icons.cloud,
      recomendacoes: [
        'Ponto de colheita',
        'Avaliar umidade dos grãos',
      ],
    ),
  ];

  /// 🍅 Estágios Fenológicos do TOMATE
  static final List<PhenologicalStageModel> _estagiosTomate = [
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Cotilédones visíveis acima do solo',
      cultura: 'tomate',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 6,
      daeMaximo: 12,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'V2',
      nome: 'Segunda Folha Verdadeira',
      descricao: 'Segunda folha verdadeira expandida',
      cultura: 'tomate',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 12,
      daeMinimo: 15,
      daeMaximo: 25,
      numeroFolhasMinimo: 2,
      numeroFolhasMaximo: 2,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'V6',
      nome: 'Sexta Folha Verdadeira',
      descricao: 'Sexta folha completamente expandida',
      cultura: 'tomate',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 16,
      daeMinimo: 25,
      daeMaximo: 40,
      numeroFolhasMinimo: 6,
      numeroFolhasMaximo: 6,
      alturaMinimaCm: 30,
      alturaMaximaCm: 50,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'R1',
      nome: 'Primeira Inflorescência',
      descricao: 'Primeira inflorescência visível',
      cultura: 'tomate',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 51,
      daeMinimo: 35,
      daeMaximo: 50,
      cor: Colors.yellow,
      icone: Icons.local_florist,
      recomendacoes: [
        'Início da fase reprodutiva',
        'Atenção à nutrição (Ca, B)',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'R2',
      nome: 'Floração da Primeira Penca',
      descricao: 'Flores abertas na primeira penca',
      cultura: 'tomate',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 61,
      daeMinimo: 45,
      daeMaximo: 60,
      cor: Colors.yellow,
      icone: Icons.local_florist,
    ),
    PhenologicalStageModel(
      codigo: 'R3',
      nome: 'Frutificação (Fruto Verde)',
      descricao: 'Primeiros frutos formados (verdes)',
      cultura: 'tomate',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 71,
      daeMinimo: 55,
      daeMaximo: 75,
      cor: Colors.green,
      icone: Icons.circle,
    ),
    PhenologicalStageModel(
      codigo: 'R4',
      nome: 'Crescimento dos Frutos',
      descricao: 'Frutos em crescimento ativo',
      cultura: 'tomate',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 75,
      daeMinimo: 65,
      daeMaximo: 85,
      cor: Colors.lightGreen,
      icone: Icons.circle,
    ),
    PhenologicalStageModel(
      codigo: 'R5',
      nome: 'Maturação (Breaker)',
      descricao: 'Frutos iniciando mudança de cor',
      cultura: 'tomate',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 81,
      daeMinimo: 75,
      daeMaximo: 95,
      cor: Colors.orange,
      icone: Icons.circle,
    ),
    PhenologicalStageModel(
      codigo: 'R6',
      nome: 'Maturação Plena',
      descricao: 'Frutos completamente maduros (vermelhos)',
      cultura: 'tomate',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 87,
      daeMinimo: 85,
      daeMaximo: 110,
      cor: Colors.red,
      icone: Icons.circle,
      recomendacoes: [
        'Ponto de colheita para consumo fresco',
        'Colher escalonadamente',
      ],
    ),
  ];

  /// 🌾 Estágios Fenológicos da AVEIA
  static final List<PhenologicalStageModel> _estagiosAveia = [
    PhenologicalStageModel(
      codigo: 'VE',
      nome: 'Emergência',
      descricao: 'Coleoptile visível acima do solo',
      cultura: 'aveia',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 10,
      daeMinimo: 7,
      daeMaximo: 14,
      cor: Colors.lightGreen,
      icone: Icons.spa,
    ),
    PhenologicalStageModel(
      codigo: 'V3',
      nome: 'Terceira Folha',
      descricao: 'Terceira folha completamente expandida',
      cultura: 'aveia',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 13,
      daeMinimo: 15,
      daeMaximo: 25,
      numeroFolhasMinimo: 3,
      numeroFolhasMaximo: 3,
      cor: Colors.green,
      icone: Icons.eco,
    ),
    PhenologicalStageModel(
      codigo: 'AF',
      nome: 'Afilhamento',
      descricao: 'Emissão ativa de afilhos',
      cultura: 'aveia',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 21,
      daeMinimo: 20,
      daeMaximo: 40,
      cor: Colors.green,
      icone: Icons.grass,
      recomendacoes: [
        'Fase crítica para produção de forragem',
        'Ou corte para cobertura verde',
      ],
    ),
    PhenologicalStageModel(
      codigo: 'EL',
      nome: 'Elongação',
      descricao: 'Alongamento dos colmos',
      cultura: 'aveia',
      categoria: StageCategory.vegetativo,
      codigoBBCH: 31,
      daeMinimo: 40,
      daeMaximo: 60,
      cor: Colors.green,
      icone: Icons.height,
    ),
    PhenologicalStageModel(
      codigo: 'EB',
      nome: 'Emborrachamento',
      descricao: 'Panícula no interior da bainha',
      cultura: 'aveia',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 45,
      daeMinimo: 60,
      daeMaximo: 75,
      cor: Colors.lightGreen,
      icone: Icons.expand,
    ),
    PhenologicalStageModel(
      codigo: 'EP',
      nome: 'Espigamento',
      descricao: 'Panícula completamente visível',
      cultura: 'aveia',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 55,
      daeMinimo: 75,
      daeMaximo: 90,
      cor: Colors.amber,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'FL',
      nome: 'Floração',
      descricao: 'Anteras visíveis',
      cultura: 'aveia',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 65,
      daeMinimo: 85,
      daeMaximo: 100,
      cor: Colors.yellow,
      icone: Icons.local_florist,
    ),
    PhenologicalStageModel(
      codigo: 'GL',
      nome: 'Grão Leitoso',
      descricao: 'Grãos com conteúdo leitoso',
      cultura: 'aveia',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 75,
      daeMinimo: 100,
      daeMaximo: 115,
      cor: Colors.amber,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'GF',
      nome: 'Grão Farináceo',
      descricao: 'Grãos com consistência farinhácea',
      cultura: 'aveia',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 85,
      daeMinimo: 115,
      daeMaximo: 130,
      cor: Colors.orange,
      icone: Icons.grain,
    ),
    PhenologicalStageModel(
      codigo: 'MF',
      nome: 'Maturação Fisiológica',
      descricao: 'Grãos duros, panícula curvada',
      cultura: 'aveia',
      categoria: StageCategory.reprodutivo,
      codigoBBCH: 92,
      daeMinimo: 130,
      daeMaximo: 150,
      cor: Colors.brown,
      icone: Icons.grain,
      recomendacoes: [
        'Ponto de colheita para grãos',
        'Ou uso para cobertura/forragem',
      ],
    ),
  ];
}

