import 'dart:convert';

/// Modelo avançado para pontos de compactação e diagnóstico do solo
class SoilCompactionPointModel {
  final int? id;
  final String pointCode; // Ex: C-001, C-002
  final int talhaoId;
  final int? safraId;
  final DateTime dataColeta;
  
  // Coordenadas georreferenciadas
  final double latitude;
  final double longitude;
  final bool isAutoGenerated; // Se foi gerado automaticamente ou manual
  
  // Dados técnicos de medição
  final double profundidadeInicio; // cm (ex: 0)
  final double profundidadeFim; // cm (ex: 20)
  final double? penetrometria; // MPa
  final double? umidade; // %
  final String? textura; // Argiloso / Arenoso / Franco
  final String? estrutura; // Boa / Moderada / Ruim
  
  // Classificação automática de compactação
  final String? nivelCompactacao; // Solto / Moderado / Alto / Crítico
  
  // Diagnósticos identificados
  final List<String>? diagnosticos; // Ex: ['compactacao', 'nematoides']
  
  // Documentação
  final String? observacoes;
  final List<String>? fotosPath;
  final bool amostraColetada;
  final String? codigoAmostra;
  
  // Resultados laboratoriais (opcional)
  final String? resultadoLaboratorio;
  final DateTime? dataResultado;

  SoilCompactionPointModel({
    this.id,
    required this.pointCode,
    required this.talhaoId,
    this.safraId,
    required this.dataColeta,
    required this.latitude,
    required this.longitude,
    this.isAutoGenerated = false,
    required this.profundidadeInicio,
    required this.profundidadeFim,
    this.penetrometria,
    this.umidade,
    this.textura,
    this.estrutura,
    this.nivelCompactacao,
    this.diagnosticos,
    this.observacoes,
    this.fotosPath,
    this.amostraColetada = false,
    this.codigoAmostra,
    this.resultadoLaboratorio,
    this.dataResultado,
  });

  /// Calcula o nível de compactação baseado na penetrometria
  String calcularNivelCompactacao() {
    if (penetrometria == null) return 'Não Medido';
    
    if (penetrometria! < 1.5) {
      return 'Solto';
    } else if (penetrometria! < 2.0) {
      return 'Moderado';
    } else if (penetrometria! < 2.5) {
      return 'Alto';
    } else {
      return 'Crítico';
    }
  }

  SoilCompactionPointModel copyWith({
    int? id,
    String? pointCode,
    int? talhaoId,
    int? safraId,
    DateTime? dataColeta,
    double? latitude,
    double? longitude,
    bool? isAutoGenerated,
    double? profundidadeInicio,
    double? profundidadeFim,
    double? penetrometria,
    double? umidade,
    String? textura,
    String? estrutura,
    String? nivelCompactacao,
    List<String>? diagnosticos,
    String? observacoes,
    List<String>? fotosPath,
    bool? amostraColetada,
    String? codigoAmostra,
    String? resultadoLaboratorio,
    DateTime? dataResultado,
  }) {
    return SoilCompactionPointModel(
      id: id ?? this.id,
      pointCode: pointCode ?? this.pointCode,
      talhaoId: talhaoId ?? this.talhaoId,
      safraId: safraId ?? this.safraId,
      dataColeta: dataColeta ?? this.dataColeta,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      profundidadeInicio: profundidadeInicio ?? this.profundidadeInicio,
      profundidadeFim: profundidadeFim ?? this.profundidadeFim,
      penetrometria: penetrometria ?? this.penetrometria,
      umidade: umidade ?? this.umidade,
      textura: textura ?? this.textura,
      estrutura: estrutura ?? this.estrutura,
      nivelCompactacao: nivelCompactacao ?? this.nivelCompactacao,
      diagnosticos: diagnosticos ?? this.diagnosticos,
      observacoes: observacoes ?? this.observacoes,
      fotosPath: fotosPath ?? this.fotosPath,
      amostraColetada: amostraColetada ?? this.amostraColetada,
      codigoAmostra: codigoAmostra ?? this.codigoAmostra,
      resultadoLaboratorio: resultadoLaboratorio ?? this.resultadoLaboratorio,
      dataResultado: dataResultado ?? this.dataResultado,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'point_code': pointCode,
      'talhao_id': talhaoId,
      'safra_id': safraId,
      'data_coleta': dataColeta.toIso8601String(),
      'latitude': latitude,
      'longitude': longitude,
      'is_auto_generated': isAutoGenerated ? 1 : 0,
      'profundidade_inicio': profundidadeInicio,
      'profundidade_fim': profundidadeFim,
      'penetrometria': penetrometria,
      'umidade': umidade,
      'textura': textura,
      'estrutura': estrutura,
      'nivel_compactacao': nivelCompactacao ?? calcularNivelCompactacao(),
      'diagnosticos': diagnosticos != null ? jsonEncode(diagnosticos) : null,
      'observacoes': observacoes,
      'fotos_path': fotosPath != null ? jsonEncode(fotosPath) : null,
      'amostra_coletada': amostraColetada ? 1 : 0,
      'codigo_amostra': codigoAmostra,
      'resultado_laboratorio': resultadoLaboratorio,
      'data_resultado': dataResultado?.toIso8601String(),
    };
  }

  factory SoilCompactionPointModel.fromMap(Map<String, dynamic> map) {
    return SoilCompactionPointModel(
      id: map['id'],
      pointCode: map['point_code'],
      talhaoId: map['talhao_id'],
      safraId: map['safra_id'],
      dataColeta: DateTime.parse(map['data_coleta']),
      latitude: map['latitude'],
      longitude: map['longitude'],
      isAutoGenerated: map['is_auto_generated'] == 1,
      profundidadeInicio: map['profundidade_inicio'],
      profundidadeFim: map['profundidade_fim'],
      penetrometria: map['penetrometria'],
      umidade: map['umidade'],
      textura: map['textura'],
      estrutura: map['estrutura'],
      nivelCompactacao: map['nivel_compactacao'],
      diagnosticos: map['diagnosticos'] != null 
          ? List<String>.from(jsonDecode(map['diagnosticos']))
          : null,
      observacoes: map['observacoes'],
      fotosPath: map['fotos_path'] != null 
          ? List<String>.from(jsonDecode(map['fotos_path']))
          : null,
      amostraColetada: map['amostra_coletada'] == 1,
      codigoAmostra: map['codigo_amostra'],
      resultadoLaboratorio: map['resultado_laboratorio'],
      dataResultado: map['data_resultado'] != null 
          ? DateTime.parse(map['data_resultado'])
          : null,
    );
  }

  String toJson() => jsonEncode(toMap());

  factory SoilCompactionPointModel.fromJson(String source) =>
      SoilCompactionPointModel.fromMap(jsonDecode(source));

  @override
  String toString() {
    return 'SoilCompactionPointModel(id: $id, pointCode: $pointCode, talhaoId: $talhaoId, penetrometria: $penetrometria MPa, nivel: $nivelCompactacao)';
  }
}

